# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tcode < Formula
  desc "A fast terminal text editor written in Go"
  homepage "https://github.com/leav-dev/tcode"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/leav-dev/tcode/releases/download/v1.0.2/tcode_darwin_amd64.tar.gz"
      sha256 "f8e9a5c1df696da93b291186f6fea79421f9c9f7833ced1447aaaa1d5cb42153"

      define_method(:install) do
        bin.install "tcode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/leav-dev/tcode/releases/download/v1.0.2/tcode_darwin_arm64.tar.gz"
      sha256 "f45c8540d6d615ee167b1ba8ea027fca91caf07a80f22d82021cb459964eb8c0"

      define_method(:install) do
        bin.install "tcode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/leav-dev/tcode/releases/download/v1.0.2/tcode_linux_amd64.tar.gz"
      sha256 "f4ee806147a5cd511d5d33d139532050d247b13f7d88369cbfb46832d9f0e71a"
      define_method(:install) do
        bin.install "tcode"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/leav-dev/tcode/releases/download/v1.0.2/tcode_linux_arm64.tar.gz"
      sha256 "abfc456cb07926893a501890371dd35941243ba681e4a9d31c9a984953b64ebe"
      define_method(:install) do
        bin.install "tcode"
      end
    end
  end

  test do
    system "#{bin}/tcode", "--version"
  end
end
