# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tcode < Formula
  desc "A fast terminal text editor written in Go"
  homepage "https://github.com/leav-dev/tcode"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/leav-dev/tcode/releases/download/v1.0.1/tcode_darwin_amd64.tar.gz"
      sha256 "247d4f67a257ab59ccd4d8a2ddcdd8bfe482eef8bb2dd8e95ffb5e0d5693be0c"

      define_method(:install) do
        bin.install "tcode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/leav-dev/tcode/releases/download/v1.0.1/tcode_darwin_arm64.tar.gz"
      sha256 "6d0d577e1d0b83e5b84e5a7eb8ef0be406d8d001d345ae3db3e5211c55be15b3"

      define_method(:install) do
        bin.install "tcode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/leav-dev/tcode/releases/download/v1.0.1/tcode_linux_amd64.tar.gz"
      sha256 "307d3cf5c0131d7d4298e79fbfa09c688cf008f201fd6887d8b49863ce9758cf"
      define_method(:install) do
        bin.install "tcode"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/leav-dev/tcode/releases/download/v1.0.1/tcode_linux_arm64.tar.gz"
      sha256 "d516cd131e0fac7d367126596ac22e6bcfbaeec7330e389e1257c64e19b7d416"
      define_method(:install) do
        bin.install "tcode"
      end
    end
  end

  test do
    system "#{bin}/tcode", "--version"
  end
end
